#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

echo "------ pre-commit start ------"

# node ./lib/getStagedFiles.js
# 执行 i18n-tool 命令
cd examples/vite-vue3 && pnpm i18n-tool extract && cd -
# pnpm i18n-tool extract
# npx i18n-tool extract

echo "------ pre-commit end ------"
